version: '3.3'

services:
  api:
    build: .

    image: crdemo:v1.6.8

    # ポートフォワーディング（ホスト側：docker側）
    # ホスト側のブラウザで実行するときは http://localhost:8888 で見れるようになる
    ports:
      - "8888:8080"

    # cledentialファイルもコピー
    # docker-compose はローカルに限る。
    # docker-compose up した場合は、cledentialファイルも含めてイメージが作成されるので、
    # 公共の環境では使っちゃだめ。
    volumes:
      - /tmp/keys/:/tmp/keys

    # ここに設定した環境変数はローカルからコピーされる
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS
      - APP_TEMPLATE_FILE
      - BUCKET_NAME
      - PROJECT_ID

    tty: true
